name: CI

on:
    push:
    pull_request:

jobs:
    build-linux:
        name: Build (Ubuntu)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Build
              shell: bash
              run: |
                  set -euo pipefail

                  chmod +x \
                      ./scripts/linux_setup.sh \
                      ./scripts/linux_git_submodules_init.sh \
                      ./scripts/linux_generate.sh \
                      ./scripts/linux_build.sh \
                      ./scripts/linux_install.sh \
                      ./scripts/linux_ci.sh

                  ./scripts/linux_ci.sh

            - name: Upload Clang Release
              if: ${{ env.ACT != 'true' }}
              uses: actions/upload-artifact@v4
              with:
                  name: open_gl_learn-linux-clang-release
                  path: build/linux_clang_install/
                  if-no-files-found: error

            - name: Upload GCC Release
              if: ${{ env.ACT != 'true' }}
              uses: actions/upload-artifact@v4
              with:
                  name: open_gl_learn-linux-gcc-release
                  path: build/linux_gcc_install/
                  if-no-files-found: error